permalink: /:categories/:title.html
url: "https://tokyoshare.github.io"
company_name: "Code&Bug"
full_name: "ホ クオク フィ"
first_name: "CODE"
last_name: "BUG"
blog_title: "CODE&BUG"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "tokyoshare"
copyright_year: "2019"
google_analytics_code: "G-DHMTQVVJPQ"
aboutme: "Sharing is caring"
medium: "https://medium.com/@gdmaxcom"
twitter: ""
github: "tokyoshare"
facebook: "huyho85"
linkedin: "https://www.linkedin.com/in/christian-ho-0728495a/"
