# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            H2Q's Blog
tagline:          'H2Q Blog'
description:      'Tokyoshare'
url:              https://tokyoshare.github.io
baseurl:          /

author:
  name:           'HuyHQ'
  url:            https://twitter.com/huyhq

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tokyoshare
