permalink: /:categories/:title.html
url: "https://tokyoshare.github.io"
full_name: "Tokyo Share"
first_name: "Tokyo"
last_name: "Share"
blog_title: "Tokyo Share"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "tokyoshare"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Share to make the world better"
twitter: ""
github: "tokyoshare"
facebook: "huyho85"
linkined_url: ""
